### ISSUE TITLE
Please add a readme

### ISSUE THREAD

**Issue by anantshri** [owtf/boilerplate-templates#1]
hi Folks,

can you please add a readme.md explaining how people can contribute templates in this project. The whole jekyll and autopublish might get a bit over the top for folks.

**Comment by viyatb** [comment]
Done. Can you review it? :)
Thanks!

**Comment by anantshri** [comment]
Looks good, I will try to add a vulnerability entry and will create a pull request. if during that i feel a need will suggest here, keeping issues till me or someone else try and test that these steps all work nicely.

**Comment by viyatb** [comment]
Sure ;)

**Comment by anantshri** [comment]
This looks good to me. I am going to keep this open for confirmation from @delta24  and @7a / @tunnelshade  once we have confirmation that Readme looks good we can close this issue.

**Comment by viyatb** [comment]
Looks perfect, closing ...
